### Question 1:

In [2]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

### Question 2:

In [11]:
lst = []  
for i in range(0, 5): 
    ele = int(input()) 
    lst.append(ele)
lst2=[]
for i in range(0, 5): 
    ele2 = int(input())  
    lst2.append(ele2)
arr = np.array(lst)
arr2=np.array(lst2)
c=np.concatenate((arr,arr2), axis=None)
c.sort(kind='mergesort')
c

1
2
3
4
5
10
9
8
7
6


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Question 3:

In [12]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 5, 6]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


### Question 4

In [20]:
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])
two_dim_arr = one_dim_arr[np.newaxis, :]
two_dim_arr #one way to convert 1d to 2d is by using newaxis method


array([[1, 2, 3, 4, 5, 6]])

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns using reshape method
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Question 5

In [13]:
## Horitzontal Stack
a = np.array([1,2,3])
b = np.array([4,5,6])
print('Horizontal Append:', np.hstack((a, b)))
print('Vertical Append:', np.vstack((a, b)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


### Question 6

In [17]:
arr=[1,2,3,4,4,4,4,5,5,5,6,7]
uni=np.unique(arr, return_counts=True) 
uni #prints the unique items


(array([1, 2, 3, 4, 5, 6, 7]), array([1, 1, 1, 4, 3, 1, 1], dtype=int64))